# Site settings
title: Nytrogen
name: Nytrogen LLC
subtitle: Agile, Real Time, Networks
email:
description: Are you Ready for Real Time Animation?
baseurl: ""
url: ""
twitter_username: nytrogenGFX
github_username: nytrogen-gfx
disqus_baseurl: ""
disqus_shortname:
permalink:
cover: "/assets/2d/header_image.jpg"
logo: "/assets/2d/nytrogen-logo.jpg"
ga_tracking_id: ""

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Nye Warburton"


# External gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

# Collections
collections:
  - talks


#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts

social:
  - name: Twitter
    icon: twitter
    username: nytrogenGFX
    url: https://twitter.com/nytrogengfx
    desc: Follow me on Twitter
    share: true

  - name: Quora
    icon: quora
    username:
    url:
    desc: Follow me on Quora
    share: false

  - name: GitHub
    icon: github
    username: Nytrogen-GFX
    url: https://github.com/nytrogen-gfx
    desc: Fork me on GitHub
    share: true

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Follow me on SoundCloud
    share: false

  - name: Steam
    icon: steam
    username:
    url:
    desc: Friend me on Steam
    share: false

  - name: Vimeo
    icon: vimeo-square
    username:
    url:
    desc: Follow me on Vimeo
    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: true

  - name: "Hacker News"
    icon: hacker-news
    username:
    url:
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/nr-logo.jpg"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/jpg"

    twitter_image: "/assets/nr-logo.jpg"
