# Site settings
title: Nytrogen
name: Nytrogen LLC
subtitle: Agile, Real Time, Networks
email:
description: Are you Ready for Real Time Animation?
baseurl: ""
url: ""
twitter_username: nytrogenGFX
github_username: nytrogen-gfx
disqus_baseurl: ""
disqus_shortname:
permalink: :title
cover: "/assets/2d/header_image.jpg"
logo: "/assets/2d/nytrogen-logo.jpg"
ga_tracking_id: ""

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Nye Warburton"


# External gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

# Collections
collections:
  - talks
